---
'*.{yml,yaml}':
  - node ./node_modules/prettier/bin/prettier.cjs --write
'*.json':
  - node ./node_modules/prettier/bin/prettier.cjs --write
# NOTE: lint-staged find the closest config file to perform operations, but would not inherit from parent.
