---
printWidth: 120
tabWidth: 2
singleQuote: true
semi: true
trailingComma: all
arrowParens: avoid
overrides:
  - files: '*.{ts,tsx}'
    options:
      parser: typescript
  - files: '*.{js,jsx}'
    options:
      parser: babel
  - files: '*.vue'
    options:
      parser: vue
  - files: '*.json'
    options:
      parser: json
  - files:
      - '.prettierrc'
      - '.lintstagedrc.yml'
    options:
      parser: yaml
