packages:
  # all packages in subdirs of packages/ and components/
  - 'packages/**'
  - 'apps/**'
  # exclude packages that are inside test directories
  - '!**/test/**'
  - '!**/example/**'

onlyBuiltDependencies:
  - esbuild
  - lmdb
  - msgpackr-extract

minimumReleaseAge: 0

allowBuilds:
  esbuild: true
  lmdb: true
  msgpackr-extract: true
