---
"*.ts":
  - ng-lint-staged lint --fix --force --
  - npm run format
  - ng-lint-staged lint --
"*.{scss,less,css}":
  - stylelint --fix
  - npm run format
  - stylelint
'*.json':
  - npm run format
