---
"*.ts":
  - ng lint ng-calculator --fix --force --lint-file-patterns
  - npm run format
  - ng lint ng-calculator --lint-file-patterns
"*.{scss,less,css}":
  - stylelint --fix
  - npm run format
  - stylelint
'*.json':
  - npm run format
