---
"*.ts":
  - ng lint ng-calculator --fix --force --lint-file-patterns
  - node ../../node_modules/prettier/bin/prettier.cjs --write
  - ng lint ng-calculator --lint-file-patterns
"*.{scss,less,css}":
  - stylelint --fix
  - node ../../node_modules/prettier/bin/prettier.cjs --write
  - stylelint
"*.json":
  - node ../../node_modules/prettier/bin/prettier.cjs --write
